name: githubactions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sendgrid

    - name: Run Pylint
      id: pylint
      run: |
        pylint **/*.py > pylint_report.txt
        pylint_score=$(tail -n 2 pylint_report.txt | head -n 1 | awk '{print $7}')
        echo "Pylint score: $pylint_score"
        echo "::set-output name=score::$pylint_score"

    - name: Analyze code with OpenAI
      id: code_analysis
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python code_analysis.py > code_analysis_report.txt
        cat code_analysis_report.txt

    - name: Send email with results
      env:
        SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        TO_EMAIL: sonum02@gmail.com
        FROM_EMAIL: prreviewer@reviewer.com
      run: |
        python send_email.py
        